### ISSUE TITLE
Amazing invalid regexp on dist build JS bundle

### ISSUE THREAD

**Issue by tdd** [jackfranklin/interactive-es6#4]
Hey Jack!

First of all, thanks a ton for this tool!  I [forked it](https://github.com/deliciousinsights/interactive-es6/tree/delicious-insights) and hacked on it like crazy today to use that as a basis for interactive ES6 training. :tada: :clap: 

It works great (although I had a significant issue with the hot reloader originally, but that's fixed now, had to upgrade some modules), but when I make the dist build to deploy somewhere, the resulting bundle yields a mammoth regex error!  See for yourself:

![screen shot 2016-01-27 at 18 40 12](https://cloud.githubusercontent.com/assets/3752/12622624/8462f050-c526-11e5-8651-e92fe15df000.png)

It's not kidding.  Googling around for error message segments has been ineffective. Any clue where this might come from? System.js is always terrible inasmuch as it obfuscates the source of uncaught exceptions most of the time :cry:

**Comment by tdd** [comment]
Hey there,

OK so two things:
- This only happens when opening `dist/index.html` as a file (`file:///`), so no actual issue there
- When open as HTTP, we then get minifier failures ("Unexpected token (") that you've already run into and fixed in `ecmascript-evaluator` (as of 0.0.6). But this repo's JSPM dependencies in `package.json` still list 0.0.3, and because this is caret (`^`), not tilde (`~`), this is a locked version. Let me PR this.

**Comment by jackfranklin** [comment]
@tdd thanks for your work debugging this, PR merged! I'd love to collab on making this better; if you have any improvements you think would be beneficial I'd love to merge them in.
